###REGISTER
POST http://localhost:3000/api/auth/register
Content-Type:application/json

{
    "username": "nikitox55",
    "password": "Nico1234",
    "nombres": "nicolas roberto",
    "apellidos": "escobar",
    "fechaNacimiento": "2004-04-24",
    "mail": "nico555@gmail.com",
    "nroTelefono": "3415456985"
}

###LOGIN
POST http://localhost:3000/api/auth/login
Content-Type:application/json

{
    "username": "nikitox55",
    "password": "Nico1234"
}

###LOGOUT
POST http://localhost:3000/api/auth/logout
###PROFILE
POST http://localhost:3000/api/auth/profile
