### GET all opiniones
GET http://localhost:3000/api/opiniones

### POST opinion
# @name createOpinion
POST http://localhost:3000/api/opiniones
Content-Type: application/json

{
  "calificacion": 5,
  "comentario": "Excelente lugar para pasar el día",
  "activity": "669d99ea03f535edd5c7aabd",
  "usuario": "669d9a3503f535edd5c7aabe"
}

### ID
@id = {{createOpinion.response.body.data.id}}

### GET opinion by ID
GET http://localhost:3000/api/opiniones/{{id}}

### Update opinion by ID
# @name updateOpinion
PUT http://localhost:3000/api/opiniones/{{id}}
Content-Type: application/json

{
  "calificacion": 4,
  "comentario": "Excelente lugar para pasar el día",
  "lugar": "667f733b2e2c094f338971ad",
  "usuario": "667f733b2e2c094f338971ad"
}

### DELETE opinion by ID
DELETE http://localhost:3000/api/opiniones/{{id}}
