### GET all serviciosExternos
GET http://localhost:3000/api/serviciosExternos

### POST servicioExterno
# @name createServicioExterno
POST http://localhost:3000/api/serviciosExternos
Content-Type: application/json

{
  
  "tipoServicio": "Alquiler de autos",
  "nombre": 3,
  "descripcion": "Alquiler de autos en todo el mundooo",
  "direccion": "Av. 9 de Julio 1234",
  "horario": "Lunes a Viernes de 10 a 12hs",
  "sitioWeb": "www.hertz.com",
  "telContacto": "123456789",
  "lugar": "667f733b2e2c094f338971ad"

}

### ID
@id = {{createServicioExterno.response.body.data.id}}

### GET servicioExterno by ID

GET http://localhost:3000/api/serviciosExternos/{{id}}


### Update servicioExterno by ID
# @name updateServicioExterno
PUT http://localhost:3000/api/serviciosExternos/{{id}}
Content-Type: application/json

{
  "tipoServicio": "Alquiler de autos",
  "nombre": "Hertz",
  "descripcion": "Alquiler de autos en todo el mundooo",
  "direccion": "Av. 9 de Julio 1234",
  "horario": "Lunes a Viernes de 10 a 12hs",
  "sitioWeb": "www.hertz.com",
  "telContacto": "12345678910"
}

### DELETE servicioExterno by ID
DELETE http://localhost:3000/api/serviciosExternos/{{id}}