### GET ALL //funciona
GET http://localhost:3000/api/usuarios 


# @name CreateUsuario
### //funciona al comentar la linea de @id = {{CreateUsuario.response.body.data.id}}
    //No valida que el nombre de usuario sea unico
POST http://localhost:3000/api/usuarios
Content-Type:application/json

{
    "nombreDeUsuario": "usuario 1",
    "nombres": "dorian",
    "apellidos": "yates",
    "fechaNacimiento": "2004-04-24",
    "mail": "fivemore@gmail.com",
    "nroTelefono": "3415454855",
    "itinerarios": ["idItinerario"]
}


//@id = {{CreateUsuario.response.body.data.id}}


### //funciona poniendo id manualmente
GET http://localhost:3000/api/usuarios/6690b479615f6c390f6ec08d


### //Aparece un error en la relacion con itinerarios, pero indicando que es de N a M y no lo es.
PUT http://localhost:3000/api/usuarios/6690b479615f6c390f6ec08d
Content-Type:application/json

{
    "nombreDeUsuario": "usuario 2",
    "nombres": "mike",
    "apellidos": "mentzer",
    "fechaNacimiento": "2004-04-24",
    "mail": "ronnie666@gmail.com",
    "nroTelefono": "3415456985",
    "itinerarios": ["idItinerario"]
}



### //funciona poniendo el id manualmente
PATCH http://localhost:3000/api/usuarios/6690b479615f6c390f6ec08d
Content-Type:application/json

{
    "nombreDeUsuario" : "nikitox4",
    "mail":"escobar.nicolas.isiutnfrro@gmail.com"

}


### POST Usuario TO DELETE //funciona al comentar la linea de @idTodelete
# @name createUsuarioToDelete
POST http://localhost:3000/api/usuarios 
Content-Type:application/json

{
    "nombreDeUsuario": "usuario 2",
    "nombres": "ronnie",
    "apellidos": "coleman",
    "fechaNacimiento": "2004-04-24",
    "mail": "ronnie666@gmail.com",
    "nroTelefono": "3415456985",
    "itinerarios": ["idItinerario"]
}

//@idToDelete = {{createUsuarioToDelete.response.body.data.id}}


### DELETE //funciona poniendo id manualmente
DELETE http://localhost:3000/api/usuarios/6690b513615f6c390f6ec08f