### GET ALL //funciona. Pero en la data del itinerario muestra los datos del usuario que posee ese itinerario, no muestra los datos del itinerario como titulo, actividades, etc.
GET http://localhost:3000/api/usuarios

###
# @name CreateUsuario
### POST
POST http://localhost:3000/api/usuarios
Content-Type:application/json

{
    "nombreDeUsuario": "nicoaslasEscobar523",
    "password": "123456Nicolas",
    "nombres": "nicolas roberto",
    "apellidos": "coleman levrone",
    "fechaNacimiento": "2024-04-24",
    "mail": "ronnie666@mdasdasdasd@ail.com",
    "nroTelefono": "3415456985"
}

###
@id = {{CreateUsuario.response.body.data.id}}

### GET ONE
//FUNCIONA
GET http://localhost:3000/api/usuarios/{{id}}


###
PUT http://localhost:3000/api/usuarios/{{id}}
//FUNCIONA. No permite modificar el campo itinerarios. Solo se puede modificar al usuario desde el itinerario.
Content-Type:application/json

{
    "nombreDeUsuario": "usuario 2",
    "nombres": "mike",
    "apellidos": "mentzer",
    "fechaNacimiento": "2004-04-24",
    "mail": "ronnie666@gmail.com",
    "nroTelefono": "3415456985"
}


###
PATCH http://localhost:3000/api/usuarios/{{id}}
//FUNCIONA
Content-Type:application/json

{
    "nombreDeUsuario" : "nikitox4",
    "mail":"escobar.nicolas.isiutnfrro@gmail.com"

}

### DELETE
//FUNCIONA
DELETE http://localhost:3000/api/usuarios/{{id}}