GET http://localhost:3000/api/itinerarios
###
# @name createItinerario

POST http://localhost:3000/api/itinerarios
Content-Type: application/json

{
    "titulo": "Itinerario 1",
    "descripcion": "Itinerario hecho para 7 dias en Disney...",
    "cantDias": 5,
    "usuario":"66ba9c9d9f6358c300a50e50"
}

###
@id = {{createItinerario.response.body.data.id}}
GET http://localhost:3000/api/itinerarios/{{id}}

###
PUT http://localhost:3000/api/itinerarios/{{id}}
Content-Type: application/json

{
    "titulo": "Itinerario 2",
    "descripcion": "Itinerario hecho para 7 dias en Disney...",
    "cantDias": 13

}


###
DELETE http://localhost:3000/api/itinerarios/{{id}}
