GET http://localhost:3000/api/itinerarios
###
# @name createItinerario


POST http://localhost:3000/api/itinerarios
Content-Type: application/json

{
    "titulo": "Itinerario 3",
    "descripcion": "Itinerario hecho para 5 dias en Disney...",
    "cantDias": 5,
    "actividades": [],
    "usuario": "6691f054294339169d28a7a8"
}
###
@id = {{createItinerario.response.body.data.id}}
GET http://localhost:3000/api/itinerarios/{{id}}

###
PUT http://localhost:3000/api/itinerarios/{{id}}
Content-Type: application/json

{
    "descripcion": "Itinerario hecho para 7 dias en Disney...",
    "cantDias": 7,
}


###
DELETE http://localhost:3000/api/itinerarios/{{id}}
