GET http://localhost:3000/api/itinerarios

# @name createItinerario
###
POST http://localhost:3000/api/itinerarios
Content-Type: application/json

{
    "titulo": "Itinerario 2",
    "descripcion": "Itinerario hecho para 7 dias en Disney...",
    "cantDias": 5,
    "actividades": [
        {
            "nombre": "Universal Studios",
            "descripcion": "Parque con atracciones...",
            "aireLibre": true
        },
        {
            "nombre": "Magic Kingdom",
            "descripcion": "Parque con atracciones...",
            "aireLibre": true
        }
    ]
}
###
@id = {{createItinerario.response.body.data.id}}
GET http://localhost:3000/api/itinerarios/{{id}}

###
PUT http://localhost:3000/api/lugares/{{id}}
Content-Type: application/json

{
    "titulo": "Itinerario 2",
    "descripcion": "Itinerario hecho para 7 dias en Disney...",
    "cantDias": 5,
    "actividades": [
        {
            "nombre": "Universal Studios",
            "descripcion": "Parque con atracciones...",
            "aireLibre": true
        },
        {
            "nombre": "Magic Kingdom",
            "descripcion": "Parque con atracciones...",
            "aireLibre": true
        }
    ],
    "transporte": "Auto"
}


###
DELETE http://localhost:3000/api/lugares/{{id}}
