GET http://localhost:3000/api/itinerarios
###
# @name createItinerario

POST http://localhost:3000/api/itinerarios
Content-Type: application/json

{
    "title": "Itinerario 1",
    "description": "Itinerario hecho para 7 dias en Disney...",
    "duration": 5,
    "user":"66d12591f495b56ba354a1ef",
    "place":"66fd97cb2e28ca23b47f2058",
    "preferences":["670037ed836f65b3ad2dd21e"]
}

###
@id = {{createItinerario.response.body.data.id}}
GET http://localhost:3000/api/itinerarios/66e320d4e04fa74c2b5154cf

###
PUT http://localhost:3000/api/itinerarios/{{id}}
Content-Type: application/json

{
    "titulo": "Itinerario 2",
    "descripcion": "Itinerario hecho para 7 dias en Disney...",
    "cantDias": 5

}
###
PATCH http://localhost:3000/api/itinerarios/{{id}}
Content-Type: application/json

{
    "cantDias": 7
}


###
DELETE http://localhost:3000/api/itinerarios/{{id}}
