GET http://localhost:3000/api/itinerarios


###
# @name createItinerario

POST http://localhost:3000/api/itinerarios
Content-Type: application/json

{
    "title": "Itinerario 1",
    "description": "Itinerario hecho para 7 dias en Disney...",
    "dayStart": "2024-10-30",
    "dayEnd": "2024-11-23",
    "user":"6722862eeed0a44e8abde61f",
    "place":"67157b64371c9028019e640c",
    "activities":["66fd97cb2e28ca23b47f2058","66fd97cb2e28ca23b47f2058"],
    "participants":[]
    
}

###
@id = {{createItinerario.response.body.data.id}}

### GET ONE
GET http://localhost:3000/api/itinerarios/{{id}}

### GET all by user
GET http://localhost:3000/api/itinerarios/user/66fc4785f2b5cf4ef633816a

###
PUT http://localhost:3000/api/itinerarios/{{id}}
Content-Type: application/json

{
    "titulo": "Itinerario 2",
    "descripcion": "Itinerario hecho para 7 dias en Disney...",
    "cantDias": 5

}
###
PATCH http://localhost:3000/api/itinerarios/{{id}}
Content-Type: application/json

{
    "cantDias": 7
}


###
DELETE http://localhost:3000/api/itinerarios/66d8801d79afc1938eea8fc9
