###REGISTER
POST http://localhost:3000/api/auth/register
Content-Type:application/json

{
    "username": "facundososabbb",
    "password": "1234Facu",
    "names": "facundo",
    "lastName": "coleman levrone",
    "dateOfBirth": "2024-04-24",
    "mail": "facu@gmailll.com",
    "phoneNumber": "3415456985",
    "isAdmin": true
}

###LOGIN
POST http://localhost:3000/api/auth/login
Content-Type:application/json

{
    "username": "facu",
    "password": "1234Facu"
}

###LOGOUT
POST http://localhost:3000/api/auth/logout
###PROFILE
POST http://localhost:3000/api/auth/profile
